apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  generation: 3
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-${CICD_GIT_BRANCH}-steamdom-master
  name: steamdom-master
  namespace: ${CICD_GIT_BRANCH}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-${CICD_GIT_BRANCH}-steamdom-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-${CICD_GIT_BRANCH}-steamdom-master
    spec:
      containers:
      - image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: IfNotPresent
        name: steamdom-master
        ports:
         - containerPort: 8000
           name: 8000tcp8000
           protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: pipeline-docker-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}